spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cxf
    password: xfxf
    url: jdbc:mysql://123.207.95.134/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true